services:
  docs:
    image: test_project_local_docs
    container_name: test_project_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./test_project:/app/test_project:z
    ports:
      - '9000:9000'
    command: /start-docs
